version: '3'

services:
  postgres:
    image: 'postgres:10.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:5.0-rc-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "flexio.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/flexio'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A flexio.blueprints.contact.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/flexio'

volumes:
  postgres:
  redis:
